export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'About us',
    headline: 'A developer collective, eager to help',
    description: 'Together, we want to help companies get away from boring, plain 24/7 websites in the pursuit of establishing a proper online presence.',
    buttonLabel: 'Learn more',
    imgStart: false,
    dark: true,
    primary: true,
    darkText: true,
    img: require('../images/svg-1.svg').default,
}