export const homeObjOne = {
    id: 'about',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'About us',
    headline: 'A developer collective, eager to help',
    description: 'Dolor excepteur ut nisi sit dolore consectetur ullamco esse sint.',
    buttonLabel: 'Learn more',
    imgStart: false,
    dark: true,
    primary: true,
    darkText: true,
    img: require('../images/svg-3.svg').default,
}

export const homeObjTwo = {
    id: 'work',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Our work',
    headline: 'Veniam nulla sunt sint proident nisi ullamco.',
    description: 'Consequat non incididunt non exercitation laborum proident occaecat.',
    buttonLabel: 'Learn more',
    imgStart: true,
    dark: false,
    primary: true,
    darkText: false,
    img: require('../images/svg-1.svg').default,
}
export const homeObjThree = {
    id: 'services',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Services',
    headline: 'Et aute mollit nostrud cupidatat ut veniam officia do cillum.',
    description: 'Qui aliqua Lorem consectetur in aliquip magna ad minim.',
    buttonLabel: 'Learn more',
    imgStart: false,
    dark: true,
    primary: true,
    darkText: true,
    img: require('../images/svg-1.svg').default,
}